// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwYdNQ2RNVOePliUX_-KbKmmy222pPeJw',
    appId: '1:685679605544:web:c3c980787af0189fdb021d',
    messagingSenderId: '685679605544',
    projectId: 'chat-app-1d984',
    authDomain: 'chat-app-1d984.firebaseapp.com',
    storageBucket: 'chat-app-1d984.appspot.com',
    measurementId: 'G-Y6RLE13HJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtMclM2yXgWyvZ81etA8Vsy-ADAfGDr2c',
    appId: '1:685679605544:android:6bf2f06f1cf97bf2db021d',
    messagingSenderId: '685679605544',
    projectId: 'chat-app-1d984',
    storageBucket: 'chat-app-1d984.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgrbAULFDdgUY3PGeOET17hC_j32R9mv8',
    appId: '1:685679605544:ios:082998f1d83162d4db021d',
    messagingSenderId: '685679605544',
    projectId: 'chat-app-1d984',
    storageBucket: 'chat-app-1d984.appspot.com',
    iosClientId: '685679605544-h26i9lj9n77oruan5nq61n60tj4hc7jt.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppSholar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgrbAULFDdgUY3PGeOET17hC_j32R9mv8',
    appId: '1:685679605544:ios:5f9e5015ef7bb230db021d',
    messagingSenderId: '685679605544',
    projectId: 'chat-app-1d984',
    storageBucket: 'chat-app-1d984.appspot.com',
    iosClientId: '685679605544-tjn1qpisaoi81qkloshn21bs49l7v2hd.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppSholar.RunnerTests',
  );
}
